### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/CompilerConstruction#2]
Mandatory:
- [x] CFG
- [x] Embellished monotone framework (k is a parameter)
- [x] Constant Propagation (interprocedural)
- [x] Strongly Live Variables (intraprocedural)
- [x] Result printing in GraphViz format
- [x] Create at least 5 example programs for each analysis and test that things work properly
- [x] Documentation (for each analysis, walk through an example showing why it works). Also, instructions on how to compile and run, the purpose of each module, what the transfer functions are, assumptions (e.g. no global variables).

Optional:
- [ ] Embellished instances of other analyses (SLV)
- [ ] Shape analysis
- [ ] Self-designed analysis
- [ ] New language constructs (e.g. return)
